protected/modules/admin/controllers/FilterController.php
<?php

class FilterController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

    public $defaultAction = "admin";

	public function filters() {
		return array(
				'accessControl', // perform access control for CRUD operations
				//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules()
	{
		return array(
				array('allow', // allow admin user to perform 'admin' and 'delete' actions
						'actions'=>array('create', 'update', 'view', 'admin','delete', 'deleteFilter'),
						'users'=>array('@'),
				),
				array('deny',  // deny all users
						'users'=>array('*'),
				),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = FilterGroup::model()->findByPk($id);

		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{

		$filtersNew = new FiltersNew;

		$parent = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id=0')), 'id', 'title');
		$catList = [];
		foreach ($parent as $key=>$val) {
			$parentSub = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id='.$key)), 'id', 'title');
			$catList[$key] = $val;
			foreach ($parentSub as $key2=>$sub) {
				$catList[$val][$key2] = $sub;
				$parentSubSubs = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id='.$key2)), 'id', 'title');
				foreach ($parentSubSubs as $key3=>$subSub) {
					$catList[$val][$sub][$key3] = $subSub;
				}
			}
		}

		if (isset($_POST['FiltersNew']) && isset($_POST['filters'])) {

			$filtersNew->name = CHtml::encode($_POST['FiltersNew']['name']);
			$filtersNew->filters = json_encode($_POST['filters']);
			if (isset($_POST['color_type'])) {
				$filtersNew->type = 1;
			}

			if ($filtersNew->validate()) {

				$filtersNew->save();

				if (isset($_POST['category_filter'])) {
					foreach ($_POST['category_filter'] as $key=>$val) {

						$modelFilter = new CategoriesFilter;
						$modelFilter->categories_id = $val;
						$modelFilter->filter_new = $filtersNew->id;
						$modelFilter->save();
					}
				}
				Yii::app()->user->setFlash('success', 'success');
				$this->redirect(array('admin'));
			}
		}

		$this->render('create', array(
			'model' => $filtersNew,
			'catList' => $catList
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$filtersNew = FiltersNew::model()->findByPk($id);

		$parent = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id=0')), 'id', 'title');
		$catList = [];
		foreach ($parent as $key=>$val) {
			$parentSub = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id='.$key)), 'id', 'title');
			$catList[$key] = $val;
			foreach ($parentSub as $key2=>$sub) {
				$catList[$val][$key2] = $sub;
				$parentSubSubs = CHtml::listData(Categories::model()->findAll(array('condition' => 'parent_id='.$key2)), 'id', 'title');
				foreach ($parentSubSubs as $key3=>$subSub) {
					$catList[$val][$sub][$key3] = $subSub;
				}
			}
		}

		$categoryFilters = CategoriesFilter::model()->findAllByAttributes(array('filter_new' => $id));

		if (isset($_POST['FiltersNew'])) {

			$filtersNew->name = CHtml::encode($_POST['FiltersNew']['name']);
//			$filtersNew->filters = json_encode($_POST['filters']);
			if (isset($_POST['color_type'])) {
				$filtersNew->type = $_POST['color_type'];
			}

			if ($filtersNew->validate()) {

				$filtersNew->update();


				if (isset($_POST['category_filter'])) {

					if ($categoryFilters) {
						foreach ($categoryFilters as $filter) {
							$filter->delete();
						}
					}

					foreach ($_POST['category_filter'] as $key=>$val) {

						$modelFilter = new CategoriesFilter;
						$modelFilter->categories_id = $val;
						$modelFilter->filter_new = $filtersNew->id;
						$modelFilter->save();
					}
				} else {
					if ($categoryFilters) {
						foreach ($categoryFilters as $filter) {
							$filter->delete();
						}
					}
				}

				Yii::app()->user->setFlash('success', 'success');
				$this->redirect(array('admin'));
			}
		}

		$this->render('update', array(
			'model' => $filtersNew,
			'catList' => $catList,
			'categoryFilters' => $categoryFilters
		));
		/*
		$filterGroup = FilterGroup::model()->findByPk($id);
		if (!$filterGroup) {
			$this->redirect(array('admin'));
		}

        $parent = CHtml::listData(CategoriesLabels::model()->with('categories')->findAll(array('condition' => 'categories.parent_id=0')), 'categories.id', 'title');
        $catList = [];
        foreach ($parent as $key=>$val) {
            $parentSub = CHtml::listData(CategoriesLabels::model()->with('categories')->findAll(array('condition' => 'categories.parent_id='.$key)), 'categories.id', 'title');
            $catList[$key] = $val;
            foreach ($parentSub as $key2=>$sub) {
                $catList[$val][$key2] = $sub;
                $parentSubSubs = CHtml::listData(CategoriesLabels::model()->with('categories')->findAll(array('condition' => 'categories.parent_id='.$key2)), 'categories.id', 'title');
                foreach ($parentSubSubs as $key3=>$subSub) {
                    $catList[$val][$sub][$key3] = $subSub;
                }
            }
        }
        $categoriesFilter = CategoriesFilter::model()->findAllByAttributes(array('filter_group_id' => $id));

		$filter = new Filter;

		$labelArr = [];
		foreach (Languages::model()->findAll() as $key=>$lang) {
			$labels = FilterLabel::model()->findAll(array('condition' => 'filter_group_id='.$id.' AND languages_id='.$lang->id));
			foreach ($labels as $k=>$label) {
				$labelArr[$key][$k] = $label;
			}
		}
		$filterLabel = FilterLabel::model()->findAll(array('condition' => 'filter_group_id='.$id, 'group' => 'filter_id'));


		$modelGroupLabel = new FilterGroupLabel;
		$filterGroupLabel = FilterGroupLabel::model()->findAll(array('condition' => 'filter_group_id='.$id));

		if(isset($_POST['Filter']) && isset($_POST['FilterLabel']) && isset($_POST['FilterGroup']) && isset($_POST['FilterGroupLabel']))
		{
			$filterGroup->attributes = $_POST['FilterGroup'];

			$save = false;
			if ($filterGroup->save()) {
				foreach (Languages::model()->findAll() as $key => $lang) {
					$filterGroupLabel = FilterGroupLabel::model()->findByAttributes(array('filter_group_id' => $id, 'languages_id' => $lang->id));
					$filterGroupLabel->attributes = $_POST['FilterGroupLabel'][$key];

					if ($filterGroupLabel->validate()) {
						$filterGroupLabel->save();
						$save = true;
					}
				}
				foreach ($_POST['FilterLabel'] as $k=>$val) {
					$filter = new Filter;
					if (isset($_POST['Filter'][$k]['id'])) {
						$filter = $this->loadModel($_POST['Filter'][$k]['id']);
					}
					$filter->attributes = $_POST['Filter'][$k];
					$filter->filter_group_id = $filterGroup->id;

					if ($filter->save()) {
						foreach (Languages::model()->findAll() as $key => $lang) {
							$filterLabel = FilterLabel::model()->findByAttributes(array('filter_id' => $filter->id, 'languages_id' => $lang->id));

							if (!$filterLabel) {
								$filterLabel = new FilterLabel;
								$filterLabel->filter_id = $filter->id;
								$filterLabel->languages_id = $lang->id;
								$filterLabel->filter_group_id = $filterGroup->id;
							}

							$filterLabel->attributes = $_POST['FilterLabel'][$k][$lang->id];
							$filterLabel->save();
						}
					}
				}
                if (isset($_POST['category_filter'])) {

					foreach ($categoriesFilter as $filtergroup) {
                        $filtergroup->delete();
					}

					foreach ($_POST['category_filter'] as $key=>$val) {
                        $categoriesFilter = new CategoriesFilter;
                        $categoriesFilter->categories_id = $val;
                        $categoriesFilter->filter_group_id = $filterGroup->id;
                        $categoriesFilter->save();
					}
				} else {
					foreach ($categoriesFilter as $filtergroup) {
                        $filtergroup->delete();
					}
				}
			}
			if ($save) {
				Yii::app()->user->setFlash('success', 'success');
				$this->redirect(array('admin'));
			} else {
				Yii::app()->user->setFlash('danger', "fail");
			}
		}

		$this->render('update',array(
			'filter' => $filter,
			'filterLabel' => $filterLabel,
			'filterGroup' => $filterGroup,
			'modelGroupLabel' => $modelGroupLabel,
			'filterGroupLabel' => $filterGroupLabel,
			'labelArr' => $labelArr,
            'catList' => $catList,
            'modelFilter' => new CategoriesFilter,
            'categoriesFilter' => $categoriesFilter
		));
		*/
	}

	public function actionDelete($id)
	{
        $filterGroup = FilterGroup::model()->findByPk($id);
        if ($filterGroup) {
            $filterGroup->delete();
            $this->redirect(array('admin'));
        }

	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
//		$filterGroups = FilterGroup::model()->with('filterGroupLabel')->findAll(array('order' => 't.id DESC'));
//		$model=new FilterGroupLabel('search');
//		$model->unsetAttributes();  // clear any default values
//		if(isset($_GET['FilterGroupLabel']))
//			$model->attributes=$_GET['FilterGroupLabel'];
//
//		$this->render('admin',array(
//			'model'=>$model,
//			'filterGroups' => $filterGroups
//		));

protected/modules/admin/views/filter/_form.php
<?php
/* @var $this FilterController */
/* @var $model Filter */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'filter-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="col-md-12">
		<div class="form-group pull-left col-md-3">
			<?php echo $form->labelEx($model,'name'); ?>
			<?php echo $form->textField($model, 'name', array('class' => 'form-control', 'placeholder' => 'Filter group')); ?>
			<br>
			<div class="clearfix">
				<div class="form-group">
					<?php $modelFilter = new CategoriesFilter; ?>
					<?php echo $form->labelEx($modelFilter,'categories_id'); ?>
					<?php echo $form->dropDownList($modelFilter,'categories_id', $catList, array('class'=>'form-control', 'empty' => 'Select category')); ?>
					<?php echo $form->error($modelFilter,'categories_id'); ?>
				</div>
				<div id="category-filter">
					<?php if (!empty($categoryFilters)): ?>
						<?php foreach ($categoryFilters as $filter): ?>
							<div>
								<i class="fa fa-minus-circle" id="<?= $filter->categories_id; ?>"></i>
								<?php echo $filter->categories->title; ?>
								<input type="hidden" value="<?= $filter->categories_id; ?>" name="category_filter[]">
							</div>
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<div class="form-group col-md-3">
			<a class="btn btn-primary" title="" data-toggle="tooltip" onclick="addFilterRow(this);" data-original-title="Add Filter">
				<i class="fa fa-plus-circle"></i>
			</a>
			<?php if (!empty($model->filters) && $model->type != 1) { ?>
				<?php $filters = json_decode($model->filters); ?>

				<?php foreach ($filters as $key => $val) { ?>
<!--					<div class="form-group relative">-->
<!--						<input class="form-control" type="text" placeholder="Filter name" name="filters[]" value="--><?//=$val;?><!--">-->
<!--						<span class="remove-span">-->
<!--							<button class="btn btn-danger" data-original-title="Remove" title="" data-toggle="tooltip"-->
<!--									type="button" onclick="$(this).parent().parent().remove();">-->
<!--								<i class="fa fa-minus-circle"></i>-->
<!--							</button>-->
<!--						</span>-->
<!--					</div>-->
				<?php }
			} ?>
		</div>

		<button type="button" class="btn btn-success btn-md pull-right" data-toggle="modal" data-target="#color_modal">Color inputs</button>

		<div id="color_modal" class="modal fade" style="display: none;">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

						<h4 class="modal-title"></h4>
					</div>
					<div class="modal-body">
						<div class="form-group" id="colors" style="">
							<a class="btn btn-primary" title="" data-toggle="tooltip" onclick="addColorRow(this);" data-original-title="Add Color Filter">
								<i class="fa fa-plus-circle"></i>
							</a>
							<input type="hidden" name="color_type" value="0">
							<?php if (!empty($model->filters) && $model->type == 1) { ?>
								<?php $filters = json_decode($model->filters); ?>

								<?php foreach ($filters as $key => $val) { ?>
									<div class="form-group relative">
										<input class="form-control" type="color" placeholder="Filter name" name="filters[]" value="<?=$val;?>">
										<span class="remove-span">
											<button class="btn btn-danger" data-original-title="Remove" title="" data-toggle="tooltip"
													type="button" onclick="$(this).parent().parent().remove();">
												<i class="fa fa-minus-circle"></i>
											</button>
										</span>
									</div>
								<?php }
							} ?>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" data-dismiss="modal" class="btn btn-default">Close</button>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="clearfix buttons text-right">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap-colorpicker.min.css">
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/bootstrap-colorpicker.min.js" type="text/javascript"></script>

<script>

	$('#color_modal').on('hidden.bs.modal', function (e) {

		var color_type = $('input[name="color_type"]');

		var color_inputs = $('#colors').find('.form-group');

		if (color_inputs.length == 0) {
			color_type.attr('value', 0);
		} else {
			color_type.attr('value', 1);
		}
	});

	var i=0;
	var n=0;
	function addFilterRow($this) {

		$($this).parent().append('<div class="form-group relative">'+
				'<input id='+i+' type="text" name="filters['+i+'][main_size]" class="form-control filter" placeholder="Filter name">'+
				'<span class="remove-span">'+
					'<button onclick="$(this).parent().parent().remove();" class="btn btn-danger" type="button" data-toggle="tooltip" title="" data-original-title="Remove">'+
						'<i class="fa fa-minus-circle"></i>'+
					'</button>'+
				'</span>'+
				'<span class="add-span">'+
					'<button onclick="addOtherSizes(this)" class="btn btn-default" type="button" data-toggle="tooltip" title="" data-original-title="Add other sizes">'+
						'<i class="fa fa-plus-circle"></i>'+
					'</button>'+
				'</span>'+
			'</div>');
		i++;
	}


	function addOtherSizes($this) {
		var main = $($this).parent().parent().find('.filter').attr('id');

//		console.log($($this).parent().parent().find('.filter').attr('id'))
		$($this).parent().parent().append('<div><input name="filters['+main+']['+n+'][other_size_name]" type="text" placeholder="Name"><input name="filters['+main+']['+n+'][other_size_val]" type="text" placeholder="value">'+
			'<button onclick="$(this).parent().remove();" class="btn btn-danger btn-sm" type="button" onclick="" data-toggle="tooltip" title="" data-original-title="Remove">'+
				'<i class="fa fa-minus-circle"></i>'+
			'</button></div>');
		n++;
	}

	function addColorRow($this) {
		$($this).parent().append('<div class="form-group relative">'+
				'<input type="color" name="filters[]" class="form-control" placeholder="Filter name">'+
				'<span class="remove-span">'+
					'<button onclick="$(this).parent().parent().remove();" class="btn btn-danger" type="button" onclick="" data-toggle="tooltip" title="" data-original-title="Remove">'+
						'<i class="fa fa-minus-circle"></i>'+
					'</button>'+
				'</span>'+
			'</div>');
	}

	function removeFilter(filter_id, e) {
		var answer = confirm('are you sure?');
		if (answer) {
			$.ajax({
				type: 'POST',
				data: {
					id: filter_id
				},
				url: '<?php echo Yii::app()->request->baseUrl;?>/admin/filter/deleteFilter',
				success: function() {
					e.remove();
				}
			})
		}
	}

	var arr = [];

	var categoryFilters = $('#category-filter').find($('.fa-minus-circle'));
	$.each(categoryFilters, function(i, v) {
		arr.push(v.id)
	})

	$('#CategoriesFilter_categories_id').change(function() {

		var categoryFilter = $('#CategoriesFilter_categories_id :selected');
		console.log(arr)
		var group_id = $('#CategoriesFilter_categories_id :selected').val();
		var filters = '';
		if ($.inArray(group_id, arr) == -1 && group_id != '') {
			filters += '<div><i class="fa fa-minus-circle" id="'+categoryFilter.val()+'"></i> ' + categoryFilter.text() + '<input type="hidden" value="' + categoryFilter.val() + '" name="category_filter[]"></div>'
			$('#category-filter').append(filters);
			arr.push(group_id);
		}

	});

	$('#category-filter').on('click', '.fa-minus-circle', function() {
		arr.splice( $.inArray($(this).attr('id'), arr), 1 );
		$(this).parent().remove();
	});

</script>

protected/modules/admin/views/filter/_search.php
<?php
/* @var $this FilterController */
/* @var $model Filter */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

    <div class="form-group">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11, 'class'=>'form-control')); ?>
	</div>

    <div class="form-group">
		<?php echo $form->label($model,'filter_group_id'); ?>
		<?php echo $form->textField($model,'filter_group_id', array('class'=>'form-control')); ?>
	</div>

    <div class="form-group">
		<?php echo $form->label($model,'sort_order'); ?>
		<?php echo $form->textField($model,'sort_order', array('class'=>'form-control')); ?>
	</div>

	<div class="clearfix buttons text-right">
		<?php echo CHtml::submitButton('Search', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/filter/_view.php
<?php
/* @var $this FilterController */
/* @var $data Filter */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('filter_group_id')); ?>:</b>
	<?php echo CHtml::encode($data->filter_group_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('sort_order')); ?>:</b>
	<?php echo CHtml::encode($data->sort_order); ?>
	<br />


</div>

protected/modules/admin/views/filter/admin.php
<?php
/* @var $this FilterController */
/* @var $model Filter */

$this->breadcrumbs=array(
	'Filters'=>array('admin'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Filter', 'url'=>array('index')),
	array('label'=>'Create Filter', 'url'=>array('create')),
);

?>

<h1>
    Manage Filters
    <?php echo CHtml::link('<i class="fa fa-plus"></i>', array('filter/create'), array('class' => 'pull-right')); ?>
</h1>

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-list"></i> Filter List</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <td class="text-left">
                                Filter Group
                            </td>

                            <td class="text-right">Action</td>
                        </tr>
                    </thead>

                    <tbody>

                        <?php
                        if (!empty($filterGroups)) {
                            foreach ($filterGroups as $group) { ?>
                                <tr>
                                    <td class="text-left"><?php echo $group->name; ?></td>

                                    <td class="text-right">
                                        <?php echo CHtml::link('<i class="fa fa-eye"></i>', array('filter/view', 'id' => $group->id)); ?>
                                        <?php echo CHtml::link('<i class="fa fa-pencil"></i>', array('filter/update', 'id' => $group->id)); ?>
                                        <?php echo CHtml::link('<i class="fa fa-remove"></i>', array('filter/delete', 'id' => $group->id), array('confirm' => 'Are you sure you want to delete this item?')); ?>
                                    </td>
                                </tr>
                            <?php }
                        } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

protected/modules/admin/views/filter/create.php
<?php
/* @var $this FilterController */
/* @var $model Filter */

$this->breadcrumbs=array(
	'Filters'=>array('admin'),
	'Create',
);

$this->menu=array(
	array('label'=>'Manage Filter', 'url'=>array('admin')),
);
?>

<h1>Create Filter</h1>

<?php $this->renderPartial('_form', array(
	'model' => $model,
	'catList' => $catList
		/*'filter'=>$filter,
		'filterGroup' => $filterGroup,
		'modelGroupLabel' => $modelGroupLabel,
        'catList' => $catList,
        'modelFilter' => $modelFilter*/
		)); ?>

protected/modules/admin/views/filter/index.php
<?php
/* @var $this FilterController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Filters',
);

$this->menu=array(
	array('label'=>'Create Filter', 'url'=>array('create')),
	array('label'=>'Manage Filter', 'url'=>array('admin')),
);
?>

<h1>Filters</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/admin/views/filter/update.php
<h1>Update Filter <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array(
	'model' => $model,
	'catList' => $catList,
	'categoryFilters' => $categoryFilters
		/*'filter' => $filter,
		'filterLabel' => $filterLabel,
		'filterGroup' => $filterGroup,
		'modelGroupLabel' => $modelGroupLabel,
		'filterGroupLabel' => $filterGroupLabel,
		'labelArr' => $labelArr,
        'catList' => $catList,
        'modelFilter' => $modelFilter,
        'categoriesFilter' => $categoriesFilter
		*/
)); ?>

protected/modules/admin/views/filter/view.php
<?php
/* @var $this FilterController */
/* @var $model Filter */

$this->breadcrumbs=array(
	'Filters'=>array('admin'),
	$model->id,
);

$this->menu=array(
	array('label'=>'Create Filter', 'url'=>array('create')),
	array('label'=>'Update Filter', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Filter', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Filter', 'url'=>array('admin')),
);
?>

<h1>View Filter #<?php echo $model->id; ?>
	<?php echo CHtml::link('<i class="fa fa-upload"></i>', array('filter/update', 'id' => $model->id), array('class' => 'pull-right')); ?>
</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		array(
			'name' => 'filter_group_id',
			'value' => function($data) {
				return $data->filterGroupLabel[0]->name;
			},
		),
		'sort_order',
	),
)); ?>

<?php if ($model->type != 'color'): ?>
	<div class="clearfix">
		<div class="nav-tabs-custom">
			<ul class="nav nav-tabs">
				<?php foreach(Languages::model()->findAll() AS $key => $language): ?>
					<li class="lang <?=$key==0?"active":""?>" lang_id="<?=$language->id?>">
						<a href="#tab_<?=$key?>" data-toggle="tab" aria-expanded="true"><?php echo CHtml::image($language->flag_url, '', array('width' => '20px')); ?> <?=$language->title?></a>
					</li>
				<?php endforeach; ?>
			</ul>
			<div class="tab-content">
				<?php foreach(Languages::model()->findAll() AS $key=>$language): ?>
					<?php $labels = FilterLabel::model()->findAllByAttributes(array('languages_id' => $language->id, 'filter_group_id' => $model->id)); ?>
					<?php if($labels): ?>

						<div class="tab-pane <?=$key==0?"active":""?>" id="tab_<?=$key?>">

							<?php foreach($labels as $label): ?>
								<label>Sort order: </label>
								<?php echo $label->filter->sort_order; ?>
								<div class="form-group">
									<label>Name: </label>
									<?php echo $label->name; ?>
								</div>
							<?php endforeach; ?>
						</div>

					<?php endif; ?>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
<?php else: ?>
	<?php foreach (FilterAdditional::model()->findAllByAttributes(array('filter_group_id' => $model->id)) as $color): ?>
		<span style="background: <?php echo $color->title; ?>; padding: 0 10px; margin: 10px;"></span>
	<?php endforeach; ?>
<?php endif; ?>