protected/modules/admin/controllers/SubscribersController.php
<?php

class SubscribersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

    public $defaultAction = "admin";

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Subscribers;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subscribers']))
		{
			$model->attributes=$_POST['Subscribers'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Subscribers']))
		{
			$model->attributes=$_POST['Subscribers'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}


	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
        $newslettersList = CHtml::listData(Newsletters::model()->findAll(array()), 'id', 'title');
        if(!empty($_POST['Subscriptions'])){
            $news_letter_id = $_POST['Subscriptions']['newsletter_id'];
            $newsletters = Newsletters::model()->findByAttributes(array('id' => $news_letter_id));

            $title = $newsletters->title;
            $description = $newsletters->description;
            foreach($_POST['Subscriptions']['subscriber_id'] as $sub){
                $model=new Subscriptions();
                $model->subscriber_id = $sub;
                $model->newsletter_id = $_POST['Subscriptions']['newsletter_id'];
                $save = $model->save();



            }

            foreach($_POST['Subscriptions']['user_id'] as $user_id){
                $userData = Users::model()->findByAttributes(array('id' => $user_id));
                $email = $userData['email'];
                if($save){
                    FrontHelpers::subscriptionEmail($title,$description, $email );
                }
            }


        }
        $subscribers = Subscribers::model()->with('subscription')->findAll();

		$this->render('admin',array(
			'model'=>new Subscriptions(),
            'subscribers' => $subscribers,
            'newslettersList' => $newslettersList
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Subscribers the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Subscribers::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Subscribers $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='subscribers-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

    public function actionFilterSubscribers(){
        if (Yii::app()->request->isAjaxRequest) {
            $subscribers = Subscriptions::model()->findAll(array('condition' => 'newsletter_id =' .$_POST['newsletter_id']));

            $arr = [];
            if(empty($subscribers)){
                $user_id = Subscribers::model()->findAll();

                foreach($user_id as $value){
                    $arr[$value['user_id']] = $value['id'];
                }
            }else{
                $already_sub = [];
                foreach($subscribers as $subscriber){
                    $already_sub[] = $subscriber->subscriber_id;
                    $test = [];
                    $user_id = Subscribers::model()->findAll();
                    foreach($user_id as $id){
                        $test[$id['user_id']] = $id['id'];
                    }

                }
                $arr = array_diff($test,$already_sub);
            }
            echo json_encode($arr);

        }
    }
}

protected/modules/admin/views/subscribers/_form.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'subscribers-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="form-group">
		<?php echo $form->labelEx($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id',array('size'=>11,'maxlength'=>11, 'class'=>'form-control')); ?>
		<?php echo $form->error($model,'user_id'); ?>
	</div>

	<div class="clearfix buttons text-right">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/admin/views/subscribers/_search.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

    <div class="form-group">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>11,'maxlength'=>11, 'class'=>'form-control')); ?>
	</div>

    <div class="form-group">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id',array('size'=>11,'maxlength'=>11, 'class'=>'form-control')); ?>
	</div>

	<div class="clearfix buttons text-right">
		<?php echo CHtml::submitButton('Search', array('class' => 'btn btn-primary')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/admin/views/subscribers/_view.php
<?php
/* @var $this SubscribersController */
/* @var $data Subscribers */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />


</div>

protected/modules/admin/views/subscribers/admin.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */

$this->breadcrumbs=array(
	'Subscribers'=>array('admin'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Subscribers', 'url'=>array('index')),
	array('label'=>'Create Subscribers', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#subscribers-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>
    Manage
    Subscribers
    <a href="/tamoda.sk/admin/Subscribers/create" class="pull-right">
        <i class="fa fa-plus"></i>
    </a>
</h1>



<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>


<?php $form=$this->beginWidget('CActiveForm', array(
    'id'=>'subscribe-form',
    'enableAjaxValidation' => false,
    'enableClientValidation'=>true,
    'clientOptions'=>array(
        'validateOnSubmit'=>true,
    ),
)); ?>

<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-list"></i> Subscribers List</h3>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
<!--                $form->dropDownList($model,'status',array(0=>'new',1 => 'used'), array('class'=>'prof-form'))-->
                <?php echo $form->dropDownList($model, 'newsletter_id', CHtml::listData(Newsletters::model()->findAll(array()), 'id', 'title'),array('class'=>'prof-form required', 'prompt' => 'Choose newsletter')); ?>
                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <td class="text-left">
                            Subscriber id
                        </td>
                        <td class="text-right">
                            Sort Order
                        </td>
                        <td class="text-right">Action</td>
                    </tr>
                    </thead>

                    <tbody>

                        <tr>
                            <td class="text-left user-check"></td>
<!--                            <td class="text-right">--><?php //echo $subscriber['user_id'] ?><!--</td>-->
<!--                            <td class="text-right">-->
<!--                                --><?php //echo CHtml::link('<i class="fa fa-eye"></i>', array('subscribers/view', 'id' => $subscriber->id)); ?>
<!--                                --><?php //echo CHtml::link('<i class="fa fa-pencil"></i>', array('subscribers/update', 'id' => $subscriber->id)); ?>
<!--                                --><?php //echo CHtml::link('<i class="fa fa-remove"></i>', array('subscribers/delete', 'id' => $subscriber->id), array('confirm' => 'Are you sure you want to delete this item?')); ?>
<!--                            </td>-->
                        </tr>

                    </tbody>
                </table>
                <?php echo CHtml::submitButton('Send', array('class' => 'btn btn-primary')); ?>
            </div>
        </div>
    </div>
</div>
<?php $this->endWidget(); ?>


<script>
    $(document).ready(function(){
        $('#Subscriptions_newsletter_id').change(function(){
            var newsletter_id = $(this).val();

            $.ajax({
                url: '<?php echo Yii::app()->request->baseUrl;?>/admin/subscribers/FilterSubscribers' ,
                type: "post",
                data: {
                    newsletter_id: newsletter_id

                },
                success: function(data)
                {
                    $('.check').remove();
                    var data1 = JSON.parse(data);
                    $.each( data1, function( key, value ) {
                        console.log(value);
                        $('.user-check').append('<span class="check"><input type="checkbox" name="Subscriptions[subscriber_id][]" value="'+value+'">'+value+'<input type="hidden" name="Subscriptions[user_id][]" value="'+key+'"><input type="hidden" name="newslatter_id" value="'+newsletter_id+'"></span>')
                    })


                }
        })
    })
})
</script>

protected/modules/admin/views/subscribers/create.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */

$this->breadcrumbs=array(
	'Subscribers'=>array('admin'),
	'Create',
);

$this->menu=array(
	array('label'=>'Manage Subscribers', 'url'=>array('admin')),
);
?>

<h1>Create Subscribers</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/subscribers/index.php
<?php
/* @var $this SubscribersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Subscribers',
);

$this->menu=array(
	array('label'=>'Create Subscribers', 'url'=>array('create')),
	array('label'=>'Manage Subscribers', 'url'=>array('admin')),
);
?>

<h1>Subscribers</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/modules/admin/views/subscribers/update.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */

$this->breadcrumbs=array(
	'Subscribers'=>array('admin'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'Create Subscribers', 'url'=>array('create')),
	array('label'=>'View Subscribers', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Subscribers', 'url'=>array('admin')),
);
?>

<h1>Update Subscribers <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/admin/views/subscribers/view.php
<?php
/* @var $this SubscribersController */
/* @var $model Subscribers */

$this->breadcrumbs=array(
	'Subscribers'=>array('admin'),
	$model->id,
);

$this->menu=array(
	array('label'=>'Create Subscribers', 'url'=>array('create')),
	array('label'=>'Update Subscribers', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Subscribers', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Subscribers', 'url'=>array('admin')),
);
?>

<h1>View Subscribers #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
	),
)); ?>