protected/modules/admin/controllers/ProductsController.php
<?php

class ProductsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public function filters() {
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create', 'update', 'view', 'admin', 'delete', 'approve', 'reject'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public $layout='//layouts/column2';

	public $defaultAction = "admin";

	public function actionAdmin($t = null)
	{
		if (isset($t)) {
			$model = Products::model()->findAllByAttributes(array('status' => CHtml::encode($t)));
		} else {
			$model = Products::model()->findAll();
		}

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id)
		));
	}

	public function actionApprove($id = null) {
		$model = $this->loadModel($id);

		if ($model) {
			$model->status = 'active';
			if ($model->save()) { //add mail
				$note = new Notifications;
				$note->user_id = $model->user->id;
				$note->text = 'Your advert ['.$model->name.'] has been approved';
				$note->save();
				$this->redirect(array('view', 'id' => $id));
			}
		}
	}

	public function actionReject($id = null) {
		$model = $this->loadModel($id);

		if ($model) {
			$model->status = 'rejected';
			if ($model->save()) { //add mail
				$note = new Notifications;
				$note->user_id = $model->user->id;
				$note->text = 'Your advert ['.$model->name.'] has been rejected';
				$note->save();
			}
			$this->redirect(array('view', 'id' => $id));
		}
	}

	public function loadModel($id)
	{
		$model=Products::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/modules/admin/controllers/ReportsController.php
<?php

class ReportsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public function filters() {
		return array(
			'accessControl', // perform access control for CRUD operations
			//'postOnly + delete', // we only allow deletion via POST request
		);
	}

	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create', 'update', 'view', 'admin', 'delete', 'approve', 'reject'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public $layout='//layouts/column2';

	public $defaultAction = "admin";

	public function actionAdmin()
	{
		
			$model = ProductsReports::model()->findAll();
		

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id)
		));
	}

	public function loadModel($id)
	{
		$model=ProductsReports::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/modules/admin/views/reports/admin.php
<?php
/* @var $this CategoriesController */
/* @var $model Categories */

?>

<h1>
	Manage Reports
</h1>
<div class="collapse navbar-collapse">
	<ul class="nav navbar-nav nav-tabs">
		<li><?php echo CHtml::link('All Reports', array('reports/')); ?></li>
	</ul>
</div>

<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">

				<div class="box-body">
					<input type="button" id="button" class="btn btn-adn" style="position: absolute;" value="Delete selected row">
					<table id="prod-table" class="table table-bordered table-hover">
						<thead>
						<tr>
							<th>Advert Name</th>
							<th>Reports type</th>
							<th>Reports Text</th>
							<th></th>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($model as $report) { ?>
							<tr id="<?php echo $report->id; ?>">
								<td><?php echo CHtml::link($report->product->name, array('products/view', 'id' => $report->product->id)); ?></td>
								<td><?php echo ProductsReports::$reportType[$report->report_type]; ?></td>
								<td><?php echo $report->report_text; ?></td>
								<td class="button-column">
									<?php echo CHtml::link('<i class="fa fa-eye"></i>', array('products/view', 'id' => $report->product_id)); ?>
								</td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div><!-- /.box-body -->
			</div><!-- /.box -->

		</div><!-- /.col -->
	</div><!-- /.row -->
</section><!-- /.content -->

<link rel="stylesheet" href="../templates/AdminLTE/plugins/datatables/dataTables.bootstrap.css">

<script src="../templates/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="../templates/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js"></script>

<script>
	$(function () {

		var table = $('#prod-table').DataTable({
			"paging": true,
			"lengthChange": false,
//			"searching": false,
			"ordering": true,
			"info": true,
			"autoWidth": false
		});

		$('#button').hide();

		$('#prod-table tbody').on( 'click', 'tr', function () {

			if ( $(this).hasClass('selected') ) {
				$(this).removeClass('selected');
				$('#button').hide();
			}
			else {
				table.$('tr.selected').removeClass('selected');
				$(this).addClass('selected');
				$('#button').show();
			}

			if ($(this).find('.parent').text() == '') {
				console.log('ssd')
			}
		});

		$('#button').click( function () {
			var answer = confirm('Are you sure you want to delete this item?');
			if (answer) {
				$.ajax({
					type: 'POST',
					data: {
						id: $('table').find('.selected').attr('id')
					},
					url: '<?php echo Yii::app()->request->baseUrl;?>/admin/reports/delete',
					success: function() {
						table.row('.selected').remove().draw( false );
					}
				})
			}

		});
	});

	var url = window.location.href;

	$('ul.nav a[href="'+ url +'"]').parent().addClass('active');

	$('ul.nav a').filter(function() {
		return this.href == url;
	}).parent().addClass('active');

</script>